
title: "Ø³Ø§ÛŒØª ØµÙ†Ø¹ØªÛŒ Ø¨Ù‡Ø³Ø§Ø² Ù…Ø§Ø´ÛŒÙ†"
baseurl: "/panel2" # ðŸ‘ˆ Ù†Ø§Ù… Ù…Ø®Ø²Ù† Ø¨Ø§ÛŒØ¯ Ø§ÛŒÙ†Ø¬Ø§ Ø¨Ø§Ø´Ù‡ Ø¨Ø§ Ø§Ø³Ù„Ø´ Ø§ÙˆÙ„
url: "https://hadishanazari.github.io"
markdown: kramdown
theme: minima