<<<<<<< HEAD
topbar_text: "تولید کننده انواع سیستم های شست و شوی صنعتی"
contact_phone: "09121234567"
test_text: "صفحه من"
=======
topbar_text: تولید کننده انواع دستگاههای نانوایی
contact_phone: "09134123005"
>>>>>>> de9a2cef89cfff777c9bfeac6b38f7c1990e915c
